# Create the folder structure of nahriva-grid-analysis with empty files.
# Snapshot of the existing project files; without dependencies and local data.
# Change the target before pasting into PowerShell if needed.
$Destination = Join-Path $env:USERPROFILE 'Desktop\nahriva-grid-analysis'
$ErrorActionPreference = 'Stop'

$Files = @'
.gitattributes
.gitignore
BIG_PICTURE.md
README.md
azure-pipelines.yml
backend/.env.example
backend/.gitignore
backend/DEBUGGING.md
backend/app/__init__.py
backend/app/analysis/__init__.py
backend/app/analysis/bootstrap.py
backend/app/analysis/migrations/002_analysis.sql
backend/app/analysis/models.py
backend/app/analysis/repository.py
backend/app/analysis/schema.py
backend/app/analysis/series.py
backend/app/core/__init__.py
backend/app/core/cache.py
backend/app/core/errors.py
backend/app/core/logging.py
backend/app/main.py
backend/app/simulation/__init__.py
backend/app/simulation/across.py
backend/app/simulation/data.py
backend/app/simulation/grids.py
backend/app/simulation/routes.py
backend/app/simulation/settings.py
backend/app/simulation/store.py
backend/pyproject.toml
backend/tests/__init__.py
backend/tests/conftest.py
backend/tests/qds_fixture.py
backend/tests/test_across_scenarios.py
backend/tests/test_analysis.py
backend/tests/test_cache.py
backend/tests/test_database_layout.py
backend/tests/test_database_selection.py
backend/tests/test_lodf.py
backend/tests/test_logging.py
backend/tests/test_powerfactory_worker.py
backend/tests/test_production.py
backend/tests/test_qds_fixture.py
backend/tests/test_simulation.py
backend/uv.lock
backend/web/fetch-assets.mjs
backend/web/package.json
deploy/windows/uninstall.ps1
docs/ASSESSMENT.md
docs/DATABASE.md
docs/DEPLOYMENT.md
docs/POWERFACTORY.md
frontend/.env.example
frontend/eslint.config.js
frontend/index.html
frontend/package-lock.json
frontend/package.json
frontend/public/favicon.svg
frontend/public/icons.svg
frontend/src/App.tsx
frontend/src/api/cache.ts
frontend/src/api/client.ts
frontend/src/assets/grid-background-dark.png
frontend/src/assets/grid-background-light.png
frontend/src/assets/hero.png
frontend/src/assets/react.svg
frontend/src/assets/vite.svg
frontend/src/components/ChartTemplatePicker.tsx
frontend/src/components/DatabasePicker.tsx
frontend/src/components/DynamicChartCard.tsx
frontend/src/components/ErrorBoundary.tsx
frontend/src/components/GridFilterProvider.tsx
frontend/src/components/GridPicker.tsx
frontend/src/components/OutageManagement.tsx
frontend/src/components/SearchableDropdown.tsx
frontend/src/components/across/AcrossChartBody.tsx
frontend/src/components/across/AcrossCharts.tsx
frontend/src/components/across/AcrossKpis.tsx
frontend/src/components/across/AcrossScenarios.tsx
frontend/src/components/across/EquipmentFilter.tsx
frontend/src/components/across/EquipmentName.tsx
frontend/src/components/across/GroupedBars.tsx
frontend/src/components/across/LazySection.tsx
frontend/src/components/across/LineScenarioHeatmap.tsx
frontend/src/components/across/LineSummaryTable.tsx
frontend/src/components/across/ScenarioDetails.tsx
frontend/src/components/across/ScenarioOptions.tsx
frontend/src/components/across/ScenarioOverview.tsx
frontend/src/components/across/ScenarioProfile.tsx
frontend/src/components/across/ScenarioRadar.tsx
frontend/src/components/across/VerdictBadge.tsx
frontend/src/components/across/VoltageMatrix.tsx
frontend/src/components/across/help.ts
frontend/src/components/across/shared.tsx
frontend/src/components/charts/BoxPlotChart.tsx
frontend/src/components/charts/BoxPlotCombinedChart.tsx
frontend/src/components/charts/Correlation3DChart.tsx
frontend/src/components/charts/CorrelationChart.tsx
frontend/src/components/charts/CorrelationMatrixChart.tsx
frontend/src/components/charts/DurationCurveChart.tsx
frontend/src/components/charts/ExceedanceChart.tsx
frontend/src/components/charts/HistogramCombinedChart.tsx
frontend/src/components/charts/ReactECharts.tsx
frontend/src/components/charts/TimeseriesChart.tsx
frontend/src/components/charts/TimeseriesHistogramChart.tsx
frontend/src/components/charts/chartPreviews.tsx
frontend/src/components/charts/chartTemplates.ts
frontend/src/components/charts/format.ts
frontend/src/components/ui/AnimatedButton.tsx
frontend/src/components/ui/CinematicThemeSwitch.tsx
frontend/src/components/ui/ColorSwatchPicker.tsx
frontend/src/components/ui/GeneratingLoader.tsx
frontend/src/components/ui/README.md
frontend/src/components/ui/cinematic-theme-switcher.tsx
frontend/src/config/assessment.ts
frontend/src/config/loadingBands.ts
frontend/src/debug/debugLog.ts
frontend/src/desktop.d.ts
frontend/src/echarts-gl.d.ts
frontend/src/hooks/useAcrossData.ts
frontend/src/hooks/useChartTheme.ts
frontend/src/hooks/useGridFilter.ts
frontend/src/hooks/useInView.ts
frontend/src/index.css
frontend/src/main.tsx
frontend/src/pages/DashboardPage.tsx
frontend/src/util/__tests__/acrossLoad.test.ts
frontend/src/util/__tests__/acrossScenarios.test.ts
frontend/src/util/__tests__/acrossSelection.test.ts
frontend/src/util/__tests__/dynamicCharts.derived.test.ts
frontend/src/util/__tests__/grids.test.ts
frontend/src/util/__tests__/outageAssessment.test.ts
frontend/src/util/__tests__/resultProvenance.test.ts
frontend/src/util/__tests__/scenarioTemplates.test.ts
frontend/src/util/__tests__/voltage.test.ts
frontend/src/util/acrossColors.ts
frontend/src/util/acrossLoad.ts
frontend/src/util/acrossScenarios.ts
frontend/src/util/acrossSelection.ts
frontend/src/util/dropdownOptions.ts
frontend/src/util/dynamicCharts.ts
frontend/src/util/grids.ts
frontend/src/util/outageAssessment.ts
frontend/src/util/resultProvenance.ts
frontend/src/util/savedView.ts
frontend/src/util/theme.ts
frontend/src/util/voltage.ts
frontend/tsconfig.app.json
frontend/tsconfig.json
frontend/tsconfig.node.json
frontend/vite.config.ts
outage-assessment.config.example.json
powerfactory/SOURCE.md
powerfactory/analysis_worker.py
powerfactory/gridlens_engine.py
powerfactory/lodf.py
powerfactory/outage_plan.py
powerfactory/pf_console.py
powerfactory/pf_state.py
powerfactory/run_summary.py
powerfactory/start_assessment.py
scripts/appconfig.py
scripts/browser-smoke.js
scripts/check.sh
scripts/dashboard_launcher.py
scripts/dev.ps1
scripts/dev.sh
scripts/package_release.py
scripts/recreate-tree.ps1
scripts/run_dashboard.py
scripts/serve.py
scripts/smoke_production.py
scripts/start_dashboard.sh
setup.cmd
setup.ps1
start-app.cmd
start-dashboard.command
stop-dashboard.cmd
stop-dashboard.ps1
'@ -split '\r?\n'

New-Item -ItemType Directory -Path $Destination -Force | Out-Null
foreach ($RelativePath in $Files) {
    if ([string]::IsNullOrWhiteSpace($RelativePath)) { continue }
    $Path = Join-Path $Destination ($RelativePath.Replace('/', '\'))
    New-Item -ItemType Directory -Path (Split-Path -Parent $Path) -Force | Out-Null
    if (-not (Test-Path -LiteralPath $Path)) {
        New-Item -ItemType File -Path $Path | Out-Null
    }
}
Write-Host "Folder and file structure created at: $Destination"
Write-Host 'Files are empty placeholders. Existing files are kept.'
